### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by EmmaSweeney** [vrajmohan/william-shakespeare_othello#1]
1. In the dramatis personae, this line:
`<p>Sailor, Messenger, Herald, Officers, Gentlemen, Musicians, and Attendants</p>`
needs to be:
`<p>Sailor, messenger, herald, officers, gentlemen, musicians, and attendants</p>`

2. There are differences between the personas in the production vs the page scans.
`<td epub:type="z3998:persona">Duke of Venice</td>` should be `<td epub:type="z3998:persona">Duke</td>`  ([Act 1, Scene 3](https://babel.hathitrust.org/cgi/pt?id=uc1.31210008566323&view=1up&seq=300)).

3. There are some places that look like this:
...
`<br/>`
`<span>DIALOGUE</span>`
`<br/>`
`<i epub:type="z3998:stage-direction">DIRECTION</i>`
`<span>DIALOGUE</span>`
`<br/>`
...

In order to insert a "major" stage direction in the  middle of dialogue, the stage direction must be in its own `<tr>` section. It would look something like this:
...
									`<br/>`
									`<span>DIALOGUE</span>`
								`</p>`
							`</td>`
						`</tr>`
						`<tr>`
							`<td/>`
							`<td>`
								`<i epub:type="z3998:stage-direction">DIRECTION</i>`
							`</td>`
						`</tr>`
						`<tr>`
							`<td/>`
							`<td epub:type="z3998:verse">`
								`<p>`
									`<span>DIALOGUE</span>`
									`<br/>`
...
You don't need to add the persona to the second part of the dialogue.

4. Some of the ending stage directions begin on a new line because of a `<br/>`. Remove this so the "minor" stage directions follow the last line of dialogue inside of the` <span>` section. If they are "major stage directions, put them in separate `<tr>` sections like seen above ([Acts and Scenes --> Stage Directions](https://standardebooks.org/contribute/how-tos/shakespeare)).

5.  In Acts 2 and 4, some dialogue is mixed in with song `<blockquote>`s. Make sure the dialogue outside the `<blockquote>`s are surrounded by `<p>`s.

6. Please run **se typogrify .** and commit the change.

7. Please run **se semanticate .** and commit the changes. Be careful! It will add roman numeral semantics to i’. Just remove them.

8. I recommend combining the second and third paragraphs in the long description.

9. long description --> Hecatommithi needs to be italicized.

10. Please remove `<meta property="se:name.person.full-name" refines="#author">CONTRIBUTOR_FULL_NAME</meta>` since it isn't used.

11. Please remove the extra space after William in `<meta property="file-as" refines="#artist">Mulready, William </meta>`.

12. long description --> “Un Capitano Moro,” needs to have quotes and italics since it is in Italian and a short story. Or you can replace it with the English translation, “A Moorish Captain,” and not use italics.

**Comment by vrajmohan** [comment]
I think I've resolved all the issues identified.

**Comment by EmmaSweeney** [comment]
I reviewed your production again and there are some stage directions that need to be moved in Act 2. These should be quick and easy to fix. I made a list of stage directions that need fixing in a second issue.
Everything else looks great! Let me know when you have made the changes.

**Comment by vrajmohan** [comment]
Sorry I missed those. Done.
