### ISSUE TITLE
Stage Direction Adjustments

### ISSUE THREAD

**Issue by EmmaSweeney** [vrajmohan/william-shakespeare_othello#2]
1. Move minor stage direction to previous `<span>` group. (Act 2, Scene 1)
...
`<span>And this, and this, the greatest discords be</span>`
`<br/>`
`<p>`
	`<i epub:type="z3998:stage-direction">Kissing her.</i>`
`</p>`
...

2. Move minor stage direction to previous `<span>` group. (Act 2, Scene 1)
...
`<span>Once more, well met at Cyprus.</span>`
`<i epub:type="z3998:stage-direction">Exeunt <b epub:type="z3998:persona">Othello</b>, <b epub:type="z3998:persona">Desdemona</b>, and Attendants.</i>`
`</p>`
...

3. Move minor stage direction to previous `<span>` group. (Act 2, Scene 1)
...
`<span>Knavery’s plain face is never seen till used.</span>`
`<i epub:type="z3998:stage-direction">Exit.</i>`
`</p>`
...

4. Move minor stage direction to previous `<span>` group. (Act 2, Scene 3)
...
`<span>That profit’s yet to come ’tween me and you.</span>`
`<br/>`
`<span>Good night.</span>`
`<i epub:type="z3998:stage-direction">Exeunt <b epub:type="z3998:persona">Othello</b>, <b epub:type="z3998:persona">Desdemona</b>, and Attendants.</i>`
`</p>`
...

5. Move minor stage direction to previous `<span>` group. (Act 2, Scene 3)
...
`<span>To cure him of this evil⁠—But, hark! what noise?</span>`
`<i epub:type="z3998:stage-direction">Cry within: “Help! help!”</i>`
`</p>`
...

6. Move minor stage direction to previous `<span>` group. (Act 2, Scene 3)
...
`<span>Nay, good lieutenant;</span>`
`<br/>`
`<i epub:type="z3998:stage-direction">Staying him.</i>`
...

7. Move minor stage direction to previous `<span>` group. (Act 2, Scene 3)
...
`<span>Help, masters!⁠—Here’s a goodly watch indeed!</span>`
`<br/>`
`<i epub:type="z3998:stage-direction">Bell rings.</i>`
...

8. Move minor stage direction to previous `<span>` group. (Act 2, Scene 3)
...
`<span>To have their balmy slumbers waked with strife.</span>`
`<i epub:type="z3998:stage-direction">Exeunt all but <b epub:type="z3998:persona">Iago</b> and <b epub:type="z3998:persona">Cassio.</b></i>`
`</p>`
...

**Comment by vrajmohan** [comment]
Thanks for the careful review. Fixed through 294050384186767d996237518bfa1cc81ee7c29a
